version: "3.8"

services:
  # -------------------
  # Selenium Grid Hub
  # -------------------
  selenium-hub:
    image: selenium/hub:4.19.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  # -------------------
  # Chrome Nodes
  # -------------------
  chrome:
    image: selenium/node-chrome:4.19.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 3

  # -------------------
  # Firefox Nodes
  # -------------------
  firefox:
    image: selenium/node-firefox:4.19.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 3
    # -------------------
    #network_name
networks:
  default:
    external:
      name: jenkins-grid-net
